### ISSUE TITLE
instance on PDBe web page not working

### ISSUE THREAD

**Issue by sillitoe** [mandarsd/pdb-topology-viewer#1]
This is probably an issue for the PDBe web pages rather than this component...

I was interested in the topology diagram for 1avb.

It didn't show up here:

http://www.ebi.ac.uk/pdbe/entry/pdb/1avb/analysis

However, updating the id on this page did work:

https://www.ebi.ac.uk/pdbe/pdb-component-library/doc.html#a_topologyViewer

**Comment by mandarsd** [comment]
Topology viewer is integrated on 'Molecular details' page in PDBe website. 
For 1avb, you can find it here : http://www.ebi.ac.uk/pdbe/entry/pdb/1avb/protein/1

**Comment by sillitoe** [comment]
Thanks for the quick response.

Ah, in that case, this can be closed and moved over as feedback for the web pages. I intuitively expected to see similar results when following these links:

Structure Analysis -> "details"
Structure Analysis -> "molecule details"

![pdbe-snapshot](https://cloud.githubusercontent.com/assets/152954/23409409/6beed724-fdc3-11e6-958b-051befdb5294.png)

(in hindsight I can see why they might be different, but that was my first impression FWIW)

**Comment by mandarsd** [comment]
Thanks for feedback Ian! I'll check if we can make it more distinguishable.
