### ISSUE TITLE
what is the algorithm used to draw protein 2D representation?

### ISSUE THREAD

**Issue by jhutar** [mandarsd/pdb-topology-viewer#2]
Hello. What is the algorithm used in pdb-topology-viewer? Is that based on HERA? Was it published somewhere?

Thank you very much in advance.

**Comment by mandarsd** [comment]
Hi, We use the PDBsum package maintained by Roman Laskowski. Here is the PDBsum publication FYR https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2686501/

**Comment by jhutar** [comment]
Thank you!
